language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Dg8GN7LJnlm7FQ1rb1vCTK2nfDRTB4lGCBEmugFkPy/1ihhOgEq6YPml9KPhwjWnaTh+e3XIwEQGqZ7RIp4xv1WJgaGVhwhomXNwqhz0WUl6OUBcGSqS3nsiF/gNyxceNgrwmkU9j4D/n0GG+O66YZ3GO5Y4+6bHPqL5/7udPr6ubwa3lErQC1+giPtszXBmUyZEAs85v6EO0+kX5u2m4rB1gSMyDIEM/Sy/hbo4ZVBf/095+qz31Wj05UHQBQT2Vuzv0ZPl2N/mbGu0jXWBSdILQnxxQ4gXa8ld8GnCLFLOnejirDT8EmJbe6bLLnpPa6jJB0pgZr0GlpeS6oflNZtvA1BfO0NVvwwpCTK792U4IQ5dZYskW87DaVBgFsQaArkyMqX73gHF/C3p2vGTHQ+9W1scEwp+LjfKl8y80yqUpIiYbavcG1vkVaim0EmIaCPtWHVKokPUuS8IW/acupc+kKSjsW1xeAD7cIgVtf2o9jjP9bjrCXSYc+w9wDNhyNi1PGSBmWhrABIcdVcUxLhqrRhTCYpHWlckQjsMVvQXQJEpnH5TE1Q6hcPDUHuEUhlMczCZQJWlbj9wzWNBcoCmL4RMnJs2LlvJF1TWvskozNznXKBeTzDZfNfq1k2mpsdC608Vuy1uc0DmLFQqeBAI8tgfIRROtGvjO5y4ewU=
  app: safe-cove-28965
  on:
    repo: bhaktiGitHub/ActivityTrackerApp
